#!/bin/bash

if [[ "${1^^}" == "-P" || "${1^^}" == "--PHYSICAL"  || "${1^^}" == "-H" || "${1^^}" == "--HARDLINK" ]]; then 
	hardLink="//H"
	shift
fi

src=$(cygpath -aw "$1")
dst=$2
if [[ "${dst:0-1}" == "/" ]]; then 
	dst=${dst}/`basename $src`
fi
dst=$(cygpath -aw "$dst")

jobTitle4win="mklink"
#mklink is not a standalone exe but a cmd-let within cmd of windows
#http://www.mingw.org/wiki/Posix_path_conversion
#https://superuser.com/questions/526736/how-to-run-internal-cmd-command-from-the-msys-shell

if [[ -d "$1" ]]; then
	echo "link dir to $2 from $1 " 1>&2
	cmd.exe //c mklink //D "$dst" "$src"   
elif [[ -f "$1" ]]; then 
	echo "link file to $2 from $1 " 1>&2
	cmd.exe //c mklink $hardLink "$dst" "$src"
else
	echo cmd //c "mklink /J '$dst' '$src'"
fi

